# Generated by Django 3.1 on 2023-04-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
        ('store', '0004_alter_product_id'),
    ]

    operations = [
    ]
