# Generated by Django 4.0.4 on 2022-07-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_id'),
        ('accounts', '0003_auto_20220711_1623'),
    ]

    operations = [
    ]
