# Generated by Django 4.0.4 on 2022-06-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'catogory', 'verbose_name_plural': 'categories'},
        ),
    ]
