# Generated by Django 4.0.4 on 2022-07-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
        ('category', '0004_alter_category_id'),
    ]

    operations = [
    ]
