# Generated by Django 4.0.4 on 2022-07-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_merge_20220714_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
