# Generated by Django 3.1 on 2023-04-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_options'),
        ('category', '0003_alter_category_options'),
    ]

    operations = [
    ]
